server:
  port: 8080

spring:
  graphql:
    websocket:
      path: /graphqlws
    schema:
      printer:
        enabled: true
    cors:
      #allowed-methods: GET,POST
      #allowed-headers: Content-Type, Authorization
      max-age: 1800s

  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  #datasource:
    #url: jdbc:tc:postgresql:13-alpine:////spring-integration-tests
    #driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
  redis:
    url: ${REDIS_URL}

  graphql:
    cors:
      allowed-origins: https://wordlepvp-frontend.oxv.io,https://www.oxv.io,https://oxv.io
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/docker-pg
    username: docker-pg
    password: docker-pg
  jpa:
    hibernate:
      ddl-auto: update

  graphql:
    cors:
      allowed-origins: http://localhost:3000

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ch.uzh.sopra.fs22.backend.wordlepvp: debug
    reactor.netty: debug
    org.springframework:
      web: debug
      http: debug
      graphql: debug
      security: debug

debug: true
